name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-20.04]
        # os: [windows-2019]
        # os: [ubuntu-20.04, windows-2019, macOS-10.15]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        env: 
            CIBW_BUILD: 'cp38-* cp39-* cp310-*'
            CIBW_SKIP: 'pp* *686* *-musllinux_*'
              
        run: python -m pip install cibuildwheel twine virtualenv numpy cython

      - name: Install libraries linux
        if: runner.os == 'linux'
        run: |
            sudo apt-get install libasound2-dev libjack-jackd2-dev
      - name: Build wheels
        run: |
            # python setup.py build_ext
            python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
      - name: Upload wheels
        env:
            TWINE_USERNAME: Eduardo.Moguillansky
            TWINE_PASSWORD: ${{ secrets.pypipass }}
        run: |
            echo $TWINE_USERNAME
            echo $TWINE_PASSWORD
            twine upload --skip-existing wheelhouse/*.whl
        continue-on-error: true
